services:
  - type: web
    name: discord-multi-bot
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 10000
